[phases.setup]
aptPkgs = []
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production tsx server/index.ts" 